# Site settings
title: "~althonos"
baseurl: ""
url: "https://althonos.github.io"

# Header settings
nick: "althonos"
source_code:
    server: "github.com"
    nick: "althonos"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
